/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:18615aec-534d-4da6-96ef-1dedc470df3d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1kbsHhHbq",
    "aws_user_pools_web_client_id": "30mn12cmo22g45rigdijl9k61a",
    "oauth": {
        "domain": "aohbackend4bebd6c3-4bebd6c3-main.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://main.drvluxx6vavkq.amplifyapp.com/",
        "redirectSignOut": "https://main.drvluxx6vavkq.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://u7fkqvyzy5bmjiyrpolbflumqm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
